global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#dmitry_semenov'
