FROM ruby:2.6-alpine

RUN apk --no-cache add --virtual .build-dependencies \
                       build-base \
    && gem install bson -v 4.3.0 \
    && gem install bson_ext -v 1.5.1 \
    && gem install puma -v 3.12.0 \
    && gem cleanup \
    && apk del .build-dependencies \
    && rm -rf /usr/lib/ruby/gems/*/cache/* \
          /var/cache/apk/* \
          /tmp/* \
          /var/tmp/*

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
