version: '3.3'
services:
  mongodb:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  ui:
    image: ${USERNAME}/ui:${TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${TAG}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${TAG}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
