---
apiVersion: apps/v1
kind: Deployment
metadata: # Блок метаданных деплоя
  name: ui
  labels:
    app: reddit
    component: ui
spec: # Блок спецификации деплоя
  replicas: 3
  # selector описывает, как ему отслеживать POD-ы. В данном случае - контроллер будет считать POD-ы с метками:
  # app=reddit И component=ui.
  selector:
    matchLabels:
      app: reddit
      component: ui
  template: # Блок описания POD-ов
    metadata:
      name: ui-pod
      # Поэтому важно в описании POD-а задать нужные метки (labels)
      labels:
        app: reddit
        component: ui
    spec:
      containers:
        - image: bbilder/ui
          name: ui
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

